<a href="https://colab.research.google.com/github/NishitSingh2023/Business-Analytics/blob/master/Ultra_basics_of_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

In [0]:
a = np.array([[1,2,3],[4,5,6]])
print(a)
a.shape = (3,2)
print(a)

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


In [0]:
a = np.array([[1,2,3], [4,5,6]])
print(a.ndim)

2


In [0]:
a = np.arange(24)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [0]:
#help(np.reshape)

print(a.reshape(2,2,2,3))

[[[[ 0  1  2]
   [ 3  4  5]]

  [[ 6  7  8]
   [ 9 10 11]]]


 [[[12 13 14]
   [15 16 17]]

  [[18 19 20]
   [21 22 23]]]]


In [0]:
x = np.array([1,2,3,4,5])
print(x.flags)


  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False



In [0]:
help(x.flags)

Help on flagsobj object:

class flagsobj(builtins.object)
 |  Methods defined here:
 |  
 |  __delitem__(self, key, /)
 |      Delete self[key].
 |  
 |  __eq__(self, value, /)
 |      Return self==value.
 |  
 |  __ge__(self, value, /)
 |      Return self>=value.
 |  
 |  __getitem__(self, key, /)
 |      Return self[key].
 |  
 |  __gt__(self, value, /)
 |      Return self>value.
 |  
 |  __le__(self, value, /)
 |      Return self<=value.
 |  
 |  __lt__(self, value, /)
 |      Return self<value.
 |  
 |  __ne__(self, value, /)
 |      Return self!=value.
 |  
 |  __new__(*args, **kwargs) from builtins.type
 |      Create and return a new object.  See help(type) for accurate signature.
 |  
 |  __repr__(self, /)
 |      Return repr(self).
 |  
 |  __setitem__(self, key, value, /)
 |      Set self[key] to value.
 |  
 |  __str__(self, /)
 |      Return str(self).
 |  
 |  ----------------------------------------------------------------------
 |  Data descriptors defined here:
 |  
 | 

In [0]:
x = [1, 2, 3]
a = np.asarray(x, dtype = float)
print(a)

[1. 2. 3.]


In [0]:
x = ((1,2,3), (4,5))
a = np.asarray(x)
print(a)

[(1, 2, 3) (4, 5)]


In [0]:
x = np.linspace(10,20,5)
print(x)

[10.  12.5 15.  17.5 20. ]


In [0]:
x = np.linspace(10,20,6, endpoint=False)
y = np.linspace(1,2,5, retstep=True)
print(x)
print(y)


[10.         11.66666667 13.33333333 15.         16.66666667 18.33333333]
(array([1.  , 1.25, 1.5 , 1.75, 2.  ]), 0.25)


In [0]:
x = np.array([[1,2],[3,4],[5,6]])
y = x[[0,1,2], [0,1,0]]
print(y)
z = x[[2,0,1], [1,1,1]]
print(z)

[1 4 5]
[6 2 4]
